### ISSUE TITLE
你好，请问有pytorch版本吗？

### ISSUE THREAD

**Issue by jiangxinke** [truthbutcher/STFGNN-PaddlePaddle#1]

**Comment by tianjianl** [comment]
抱歉没有诶...公司所有的训练都是PaddlePaddle框架下的，和PyTorch非常像。
原MXNet模型在https://github.com/MengzhangLI/STFGNN    
这是PaddlePaddle到PyTorch的API映射表：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/08_api_mapping/pytorch_api_mapping_cn.html

**Comment by jiangxinke** [comment]
感谢你！
